### ISSUE TITLE
--pod doesn't work if pods enabled

### ISSUE THREAD

**Issue by amk221** [DudaDev/ember-cli-sass-pods#11]
When I run the example from the README

`ember g style components/contact-box -p`

The `taskOptions` contains `{"pod":false}`

If I omit the `-p` the opposite happens

The `taskOptions` contains `{"pod":true}`

Not sure if this is an ember-cli issue rather than an ember-cli-sass-pods issue

**Comment by justtal** [comment]
If you have:

// .ember-cli
{
    "usePods": true
}

then the -p does the opposites and set the pod to true.

If you don't have usePods: true, then -p should work fine.

It is ember-cli feature.

**Comment by amk221** [comment]
It's a feature... right ok! 
Thanks!
