### ISSUE TITLE
component styles are not watched?

### ISSUE THREAD

**Issue by janwerkhoven** [DudaDev/ember-cli-sass-pods#14]
I've added a `style.scss` file to each of my component pods. When I save styles within `/app/styles` the CSS is successfully compiled, including the component pod styles. However when I save the styles `/app/components/pod-name` no compilation happens...

This is quiet crucial. Is this possible?

```
app/components/product-row/template.hbs
app/components/product-row/component.js
app/components/product-row/styles.scss

app/styles/app.scss >>> @import "pods";
app/styles/pod.scss >>> @import "app/components/product-row/style";
```

**Comment by Mas-Tool** [comment]
I have the same problem.
To solve this, I modified ember-cli-build.js file to have:
  var app = new EmberApp(defaults, {
   sassOptions: { includePaths: ['app']}
    // Add options here
  });

**Comment by JawsomeJason** [comment]
It would be really great if this was done by default.  I had hours of frustration with this.

**Comment by janwerkhoven** [comment]
@Mas-Tool That worked! I have been looking for this sooo long. Thanks.

``` javascript
// ember.cli-build.js

  var app = new EmberApp(defaults, {
    sassOptions: {
      includePaths: ['app/components']
    }
  });

```

**Comment by janwerkhoven** [comment]
@thejase makes a good point.

Ember is moving away from the classic MVC and is moving towards pod structured routable components. Ember-cli-sass-pods should support pod styles this by default.

Example of routable components:

```
app/components/products-page/route.js
app/components/products-page/template.hbs
app/components/products-page/component.js
app/components/products-page/style.scss

app/components/product-row/template.hbs
app/components/product-row/component.js
app/components/product-row/style.scss
```

**Comment by justtal** [comment]
Thanks guys! I added it to the readme file. It was there before , don't know why I removed it.
