### ISSUE TITLE
Work together?

### ISSUE THREAD

**Issue by ebryn** [DudaDev/ember-cli-sass-pods#2]
Hey, looks like you guys might be interested in: https://github.com/ebryn/ember-component-css

We're pretty close to landing SASS support and could use some help rather than have several projects that do roughly the same thing.

**Comment by justtal** [comment]
Hey Erik,

We use ember-cli-sass-pods in couple internal projects in [Duda](http://dudamobile.com) so we will keep updating and support our addon.

But, it will also be great to contribute to your awesome ember-component-css addon :)

Thanks for your time,

Duda Dev Dudes.

**Comment by ebryn** [comment]
Alright, thanks :)
