### ISSUE TITLE
File naming and sourcemaps problem.

### ISSUE THREAD

**Issue by Sinled** [DudaDev/ember-cli-sass-pods#5]
At first many thanks for this handy plugin, it eased my pain.

But There is small issue when debugging with sourcemaps, 
![screenshot 2015-07-08 14 50 01](https://cloud.githubusercontent.com/assets/1402135/8569514/1a92c2f8-2581-11e5-927c-cd3255e8e007.png)

When all files named `style.scss` it is hard to understand from where current styles are coming from.

May be there is some solution for this?

**Comment by justtal** [comment]
Hey Sinled,

You can see the path to the style file if you'll stand on the style.scss link. I'll check if there is any way to do it better.

Thanks!

Tal.
