### ISSUE TITLE
Generated style breaks imports

### ISSUE THREAD

**Issue by bj-mcduck** [DudaDev/ember-cli-sass-pods#7]
When I run the generate command, the line added to `pods.scss` is:

```
@import "pods/...thing-that-im-podding";
```

But it only works if I change it to:

```
@import "app/pods/...thing-that-im-podding";
```

Along with my stack info below, I'm using `ember-cli-sass-pods 1.0.9`

```
-------------------------------
Ember             : 1.13.3
Ember Data        : 1.0.0-beta.18
Firebase          : 2.2.7
EmberFire         : 1.4.7
jQuery            : 1.11.3
Ember Simple Auth : 0.8.0
-------------------------------
```

**Comment by bj-mcduck** [comment]
Is there a configuration option that I missed, or is this an anomaly?

**Comment by justtal** [comment]
Hey Brandon,

I'll check it as soon as possible.

**Comment by justtal** [comment]
Hey, I updated the npm version.

Please install last version (1.1.0) and it should work.
