### ISSUE TITLE
Pods file does not get recompiled if includePaths is not specified

### ISSUE THREAD

**Issue by varoot** [DudaDev/ember-cli-sass-pods#8]
After upgrading to 1.1.0, the commit history says "Remove the need for includePath configuration.", but after I removed the configuration, changes to stylesheets in pods folders didn't get recompiled while the server is running, even when the file change is detected by watchman and the server.

Adding back "includePaths" option solves the problem. I'm not sure if this is a bug or am I missing something here?

**Comment by justtal** [comment]
Let me check that...

**Comment by tsing80** [comment]
confirm also. the generated styles is not updated until server is restarted  or  { sassOptions: includePaths: ['app'] }  is used in ember-cli-build.js

**Comment by Jeffrey-van-Ham** [comment]
Same here

**Comment by RobbieTheWagner** [comment]
I am also having this problem. Any updates?

**Comment by justtal** [comment]
See readme file:

https://github.com/DudaDev/ember-cli-sass-pods#watched-folder
