### ISSUE TITLE
podModulePrefix deprecated

### ISSUE THREAD

**Issue by greyhwndz** [DudaDev/ember-cli-sass-pods#9]
Hi. May I ask what is the context of "podModulePrefix deprecated" (in README.md - The import file)?
is it deprecated in ember-cli? or its use in importing in ember-cli-sass-pods?

**Comment by justtal** [comment]
Ember Cli removed the podModulePrefix in 0.2.4:
https://github.com/ember-cli/ember-cli/blob/master/CHANGELOG.md#024

But now I can see they revert it:
https://github.com/ember-cli/ember-cli/blob/master/CHANGELOG.md#026

Thanks for the notice!
